const units = [
    "mm",
    "millimeter",
    "millimeters",
    "cm",
    "centimeter",
    "centimeters",
    "m",
    "meter",
    "meters",
    "km",
    "kilometer",
    "kilometers",
    "in",
    "inch",
    "inches",
    "yd",
    "yard",
    "yards",
    "ft-us",
    "us survey foot",
    "us survey feet",
    "ft",
    "foot",
    "feet",
    "mi",
    "mile",
    "miles",
    "mm2",
    "square millimeter",
    "square millimeters",
    "cm2",
    "centimeter",
    "centimeters",
    "m2",
    "square meter",
    "square meters",
    "ha",
    "hectare",
    "hectares",
    "km2",
    "square kilometer",
    "square kilometers",
    "in2",
    "square inch",
    "square inches",
    "yd2",
    "square yard",
    "square yards",
    "ft2",
    "square foot",
    "square feet",
    "ac",
    "acre",
    "acres",
    "mi2",
    "square mile",
    "square miles",
    "mm3",
    "cubic millimeter",
    "cubic millimeters",
    "cm3",
    "cubic centimeter",
    "cubic centimeters",
    "ml",
    "millilitre",
    "millilitres",
    "cl",
    "centilitre",
    "centilitres",
    "dl",
    "decilitre",
    "decilitres",
    "l",
    "litre",
    "litres",
    "kl",
    "kilolitre",
    "kilolitres",
    "m3",
    "cubic meter",
    "cubic meters",
    "km3",
    "cubic kilometer",
    "cubic kilometers",
    "krm",
    "matsked",
    "matskedar",
    "tsk",
    "tesked",
    "teskedar",
    "msk",
    "matsked",
    "matskedar",
    "kkp",
    "kaffekopp",
    "kaffekoppar",
    "glas",
    "glas",
    "glas",
    "kanna",
    "kanna",
    "kannor",
    "tsp",
    "teaspoon",
    "teaspoons",
    "tbs",
    "tbsp", // manual
    "tablespoon",
    "tablespoons",
    "in3",
    "cubic inch",
    "cubic inches",
    "fl-oz",
    "fluid ounce",
    "fluid ounces",
    "cup",
    "cup",
    "cups",
    "pnt",
    "pint",
    "pints",
    "qt",
    "quart",
    "quarts",
    "gal",
    "gallon",
    "gallons",
    "ft3",
    "cubic foot",
    "cubic feet",
    "yd3",
    "cubic yard",
    "cubic yards",
    "mcg",
    "microgram",
    "micrograms",
    "mg",
    "milligram",
    "milligrams",
    "g",
    "gram",
    "grams",
    "kg",
    "kilogram",
    "kilograms",
    "mt",
    "metric tonne",
    "metric tonnes",
    "oz",
    "ounce",
    "ounces",
    "lb",
    "pound",
    "pounds",
    "t",
    "ton",
    "tons"
]

export default units;